### ISSUE TITLE
About page maken

### ISSUE THREAD

**Issue by TimBlommestijn** [Project-8-8AMO12/8AMO2_Groep4#1]

**Comment by ChristiaanvanHaasteren** [comment]
Op de about pagina moet er informatie komen over het bedrijf imkersleiden. Denk hierbij aan wat zij doen en wie zij zijn, en waarom zij het op hebben gericht. Neem een voorbeeld van de about pagina op de imkersleiden site.

**Comment by ChristiaanvanHaasteren** [comment]
Alleen het aanpassen van de pagina via de admin panel mist nu nog, de frontend is klaar.

**Comment by ChristiaanvanHaasteren** [comment]
De about page heeft nu ook de mogelijkheid om de text aan te passen via het admin panel.
